//
// Created by Mete Akgun on 03.07.20.
//

#ifndef PML_CONSTANT_H
#define PML_CONSTANT_H

#define L_BIT 64
#define LP 67
#define SP 7
#define FRAC 0
#define RING_N 0xffffffffffffffff  // ring size
#define N1_MASK 0x7fffffffffffffff
#define N1 0x8000000000000000
#define EVEN_MASK 0xfffffffffffffff7

#define MAXMUL 16384

#define PRECISION 100
#define MAX_SAMPLE 0xfffff
#define MAX_SAMPLE_MASK 0x7ffff

#define MAX_MATRIX_SIZE 20000
#define BUFFER_SIZE 600000000

#define DEBUG_FLAG 0


// constants for INVSQRT
#define ORTHMASK 0x3e000
#define MAX_DELTA 100
#define MIN_DELTA 100
#define MAXSCALAR 0xfffff
#define MAXA 0x3fffff

// constants for sockets
#define SCKNUM 6

enum role {
    P1, P2, HELPER
};

enum op {
    // Core
    CORE_MMSB,CORE_END,CORE_MUL,CORE_MMUL,CORE_MUX,CORE_MMUX,CORE_MMC,CORE_MC,CORE_MCMP,CORE_CMP,CORE_MSB,
    CORE_EXP, CORE_MEXP,CORE_DP,CORE_MDP,CORE_MATMATMUL,CORE_MMATMATMUL,CORE_MATVECMUL,CORE_MMATVECMUL, CORE_DIV,
    CORE_MDIV, CORE_MNORM, CORE_MMUL2,
    CORE_SORT, CORE_SORT2,
    //BOOLEAN CORE
    BCORE_AND, BCORE_SUB, BCORE_A2B, BCORE_B2A, BCORE_B2As,BCORE_B2Am,
    // AUC
    AUC_MSB,AUC_TDIV,AUC_MROU,AUC_MDIV,AUC_ROCNOTIE,AUC_ROCWITHTIE,AUC_PR,
    // CNN
    CNN_MAX, CNN_MMAX, CNN_ARGMAX, CNN_RELU, CNN_MRELU, CNN_DRLU, CNN_MDRLU, CNN_CL, CNN_FCL,
    // RKN
    RKN_EIG, RKN_MEIG, RKN_GM2KM, RKN_INVSQRT, RKN_MINVSQRT, RKN_ITER
};


#endif //PML_CONSTANT_H
